apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-deployment
  labels:
    app: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: metrics
        image: adoborroto/sample-keda-metrics-api:latest
        ports:
        - containerPort: 8090
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: metrics
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 31111
